USE Master
GO
IF DB_ID('TEC') IS NOT NULL
	BEGIN
		ALTER DATABASE TEC SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
		DROP DATABASE TEC
	END
GO
CREATE DATABASE TEC
GO
USE TEC
GO

DROP TABLE IF EXISTS Student;
CREATE TABLE Student (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(255),
    LastName NVARCHAR(255),
);

DROP TABLE IF EXISTS Teacher;
CREATE TABLE Teacher (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(255),
    LastName NVARCHAR(255)
);

CREATE TABLE Course (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    [Name] NVARCHAR(255),
    TeacherId INT FOREIGN KEY REFERENCES Teacher(Id)
);

CREATE TABLE Enrollment (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    StudentId INT FOREIGN KEY REFERENCES Student(Id),
    CourseId INT FOREIGN KEY REFERENCES Course(Id)
);
